// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonHumidity: typeof import('~icons/carbon/humidity')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CiCloseBig: typeof import('~icons/ci/close-big')['default']
    CiHamburger: typeof import('~icons/ci/hamburger')['default']
    CilHamburgerMenu: typeof import('~icons/cil/hamburger-menu')['default']
    CodiconArrowSmallRight: typeof import('~icons/codicon/arrow-small-right')['default']
    CustomIconDewPoint: typeof import('./../../../../../../package/src/icons/icon-components/CustomIconDewPoint.vue')['default']
    CustomIconEasel: typeof import('./../../../../../../package/src/icons/icon-components/CustomIconEasel.vue')['default']
    CustomIconGauge: typeof import('./../../../../../../package/src/icons/icon-components/CustomIconGauge.vue')['default']
    CustomIconPalm: typeof import('./../../../../../../package/src/icons/icon-components/CustomIconPalm.vue')['default']
    CustomIconUmbrella: typeof import('./../../../../../../package/src/icons/icon-components/CustomIconUmbrella.vue')['default']
    DashiconsVisibility: typeof import('~icons/dashicons/visibility')['default']
    FluentArrowEnterLeft20Filled: typeof import('~icons/fluent/arrow-enter-left20-filled')['default']
    FluentDelete24Regular: typeof import('~icons/fluent/delete24-regular')['default']
    HumidityInfo: typeof import('./../../package/src/components/HumidityInfo.vue')['default']
    IcSharpVisibility: typeof import('~icons/ic/sharp-visibility')['default']
    LocationHandle: typeof import('./../../package/src/components/LocationHandle.vue')['default']
    LocationInput: typeof import('./../../package/src/components/LocationInput.vue')['default']
    LocationLabel: typeof import('./../../package/src/components/LocationLabel.vue')['default']
    LocationLable: typeof import('./../../package/src/components/LocationLable.vue')['default']
    MainInfo: typeof import('./../../package/src/components/MainInfo.vue')['default']
    MdiTools: typeof import('~icons/mdi/tools')['default']
    OcticonGear16: typeof import('~icons/octicon/gear16')['default']
    PressureIndicator: typeof import('./../../package/src/components/PressureIndicator.vue')['default']
    PressureInfo: typeof import('./../../package/src/components/PressureInfo.vue')['default']
    SettingsPopup: typeof import('./../../package/src/components/SettingsPopup.vue')['default']
    VisibilityInfo: typeof import('./../../package/src/components/VisibilityInfo.vue')['default']
    WaitingSpinner: typeof import('./../../package/src/components/WaitingSpinner.vue')['default']
    WeatherCard: typeof import('./../../package/src/components/WeatherCard.vue')['default']
    WeatherIcon: typeof import('./../../package/src/components/WeatherIcon.vue')['default']
    WelcomeView: typeof import('./../../package/src/components/WelcomeView.vue')['default']
    WidgetHeader: typeof import('./../../package/src/components/WidgetHeader.vue')['default']
    WiHumidity: typeof import('~icons/wi/humidity')['default']
    WindDirectionIndicator: typeof import('./../../package/src/components/WindDirectionIndicator.vue')['default']
    WindInfo: typeof import('./../../package/src/components/WindInfo.vue')['default']
  }
}

export { }
