// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CustomIconEasel: typeof import('./../../../../../../src/icons/icon-components/CustomIconEasel.vue')['default']
    HumidityInfo: typeof import('./components/HumidityInfo.vue')['default']
    LocationInput: typeof import('./components/LocationInput.vue')['default']
    LocationLabel: typeof import('./components/LocationLabel.vue')['default']
    MainInfo: typeof import('./components/MainInfo.vue')['default']
    MdiTools: typeof import('~icons/mdi/tools')['default']
    PressureInfo: typeof import('./components/PressureInfo.vue')['default']
    SettingsPopup: typeof import('./components/SettingsPopup.vue')['default']
    VisibilityInfo: typeof import('./components/VisibilityInfo.vue')['default']
    WaitingSpinner: typeof import('./components/WaitingSpinner.vue')['default']
    WeatherCard: typeof import('./components/WeatherCard.vue')['default']
    WeatherIcon: typeof import('./components/WeatherIcon.vue')['default']
    WelcomeView: typeof import('./components/WelcomeView.vue')['default']
    WidgetHeader: typeof import('./components/WidgetHeader.vue')['default']
    WindDirectionIndicator: typeof import('./components/WindDirectionIndicator.vue')['default']
    WindInfo: typeof import('./components/WindInfo.vue')['default']
  }
}

export { }
