// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonHumidity: typeof import('~icons/carbon/humidity')['default']
    CiCloseBig: typeof import('~icons/ci/close-big')['default']
    CodiconArrowSmallRight: typeof import('~icons/codicon/arrow-small-right')['default']
    CustomIconDewPoint: typeof import('./../../../../../../src/icons/icon-components/CustomIconDewPoint.vue')['default']
    CustomIconEasel: typeof import('./../../../../../../src/icons/icon-components/CustomIconEasel.vue')['default']
    CustomIconPalm: typeof import('./../../../../../../src/icons/icon-components/CustomIconPalm.vue')['default']
    DashiconsVisibility: typeof import('~icons/dashicons/visibility')['default']
    FluentArrowEnterLeft20Filled: typeof import('~icons/fluent/arrow-enter-left20-filled')['default']
    FluentDelete24Regular: typeof import('~icons/fluent/delete24-regular')['default']
    HumidityInfo: typeof import('./components/HumidityInfo.vue')['default']
    LocationHandle: typeof import('./components/LocationHandle.vue')['default']
    LocationInput: typeof import('./components/LocationInput.vue')['default']
    MainInfo: typeof import('./components/MainInfo.vue')['default']
    MdiTools: typeof import('~icons/mdi/tools')['default']
    OcticonGear16: typeof import('~icons/octicon/gear16')['default']
    PressureIndicator: typeof import('./components/PressureIndicator.vue')['default']
    PressureInfo: typeof import('./components/PressureInfo.vue')['default']
    SettingsPopup: typeof import('./components/SettingsPopup.vue')['default']
    VisibilityInfo: typeof import('./components/VisibilityInfo.vue')['default']
    WaitingSpinner: typeof import('./components/WaitingSpinner.vue')['default']
    WeatherCard: typeof import('./components/WeatherCard.vue')['default']
    WeatherIcon: typeof import('./components/WeatherIcon.vue')['default']
    WelcomeView: typeof import('./components/WelcomeView.vue')['default']
    WidgetHeader: typeof import('./components/WidgetHeader.vue')['default']
    WindDirectionIndicator: typeof import('./components/WindDirectionIndicator.vue')['default']
    WindInfo: typeof import('./components/WindInfo.vue')['default']
  }
}

export { }
